# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
      - 'master'
      - 'release/*'

pr:
- '*'

variables:
- name: BuildNumber
  value: $[counter('buildnumber')]

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-latest
      Windows:
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)
  steps:
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: login
      containerRegistry: dockerHub
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: dockerHub
      tags: |
        $(vmImage)
  