---
- name: Check Page Content
  hosts: localhost
  connection: local
  tasks:
  - name: Check if web page loads and contains commmit
    uri: 
      url: "https://{{hostvars[item].domain}}"
      return_content: true
    register: response
    failed_when: "commitSHA not in response.content"
    with_items: "{{ groups['all'] }}"
