---
- name: Check Page Content
  hosts: all
  connection: local
  tasks:
  - name: Check if web page loads and contains commmit
    uri: 
      url: https://"{{domain}}"
      return_content: true
    register: response
    failed_when: "commitSHA not in response.content"
