---
- name: Deployment Preparation
  hosts: localhost
  connection: local
  tasks:
  - name: Create hostvars group
    lineinfile:
      path: "{{ ansible_env.GITHUB_WORKSPACE }}/inventory"
      line: "[containers]"
      create: yes

  - name: Create Container hostvars
    lineinfile:
      path: "{{ ansible_env.GITHUB_WORKSPACE }}/inventory"
      line: DigitalOceanContainer1 ansible_user=root ansible_ssh_host={{ansible_env.digitalOceanIP}} domain={{ansible_env.domain}} containerName={{ansible_env.dockerHubContainerName}} containerImage='{{ansible_env.dockerHubUsername}}/{{ansible_env.dockerHubContainerName}}:ubuntu' ansible_ssh_private_key_file=key.txt ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
      create: yes

  - name: Create Private Key File
    lineinfile: 
      path: "{{ ansible_env.GITHUB_WORKSPACE }}/key.txt"
      line: "{{ ansible_env.digitalOceanPrivateKey }}"
      create: yes

  - name: Set File Permission For Scripts
    file:
      path: "{{ ansible_env.GITHUB_WORKSPACE }}/scripts/"
      mode: '0775'

  - name: Set File Permissions for Private Key
    file:
      path: "{{ ansible_env.GITHUB_WORKSPACE }}/key.txt"
      mode: '0600'
