---
- name: Deploy
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Run Container
      docker_container: 
          image: "{{containerImage}}"
          pull: yes
          recreate: yes
          state: started
