name: Integration

on: 
  pull_request:
    branches: 
      - master
jobs:

  BuildContainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      run: echo ${{secrets.dockerHubPassword}} | docker login -u ${{secrets.dockerHubUsername}} --password-stdin
    - name: Docker Build
      run: docker build -f "dotnet3.Dockerfile" -t  ${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}} .
    - name: Push to Docker Hub
      run: docker push ${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}}:latest
    - name: Docker Hub Logout
      run: docker logout
    - name: Archive scripts for later jobs
      uses: actions/upload-artifact@v1
      with:
        name: scripts
        path: scripts

  ProductionDeploy:
    runs-on: ubuntu-latest
    needs: BuildContainer
    steps:
    - name: Get Scripts
      uses: actions/download-artifact@v1
      with:
        name: scripts
    - name: Prepare Environment
      shell: bash
      run: |
        chmod -R a+x scripts
        echo "${{secrets.digitalOceanPrivateKey}}" >> key.txt
        chmod 600 key.txt
        echo "export dockerHubUsername=${{secrets.dockerHubUserName}}" > vars
        echo "export dockerHubContainerName=${{secrets.dockerHubContainerName}}" >> vars
        echo "export GITHUB_SHA=$GITHUB_SHA" >> vars
        chmod 775 vars
        cat vars
    - name: Deploy Container
      run: ssh -o "StrictHostKeyChecking=no" -i key.txt root@${{secrets.digitalOceanIP}} 'bash -s' < scripts/containermaint.sh
    - name: Delete Private Key Text File
      run: rm key.txt
    - name: Check Page Content
      run: scripts/checkpage.sh
