name: Integration

on: 
  pull_request:
    branches: 
      - master
jobs:

  BuildContainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      run: echo ${{secrets.dockerHubPassword}} | docker login -u ${{secrets.dockerHubUsername}} --password-stdin
    - name: Docker Build
      run: docker build -f "dotnet3.Dockerfile" -t  ${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}} .
    - name: Push to Docker Hub
      run: docker push ${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}}:latest
    - name: Docker Hub Logout
      run: docker logout
    - name: Archive scripts for later jobs
      uses: actions/upload-artifact@v1
      with:
        name: scripts
        path: scripts

  Deploy:
    runs-on: ubuntu-latest
    needs: BuildContainer
    env:
      digitalOceanIP: ${{secrets.digitalOceanIP}}
      dockerHubUsername: ${{secrets.dockerHubUsername}}
      dockerHubContainerName: ${{secrets.dockerHubContainerName}}      
    steps:
    - name: Get Scripts
      uses: actions/download-artifact@v1
      with:
        name: scripts
    - name: Print Ansible Version
      run: ansible --version
    - name: Prepare Environment
      shell: bash
      run: |
        chmod -R a+x scripts
        echo "${{secrets.digitalOceanPrivateKey}}" >> key.txt
        chmod 600 key.txt
        echo "ProductionDocker ansible_host=${{secrets.digitalOceanIP}} domain=serviceno.com" > inventory
    - name: Deploy Container
      run: ansible-playbook -i inventory Deploy.yml --private-key=key.txt
    - name: Delete Private Key Text File
      run: rm key.txt
