name: Ubuntu Production Container Test

on: 

  pull_request:
    branches: 
      - master

jobs:

  BuildDeployTestContainer:
    runs-on: ubuntu-latest
    env:
      digitalOceanIP: ${{secrets.digitalOceanIP}}
      dockerHubUsername: ${{secrets.dockerHubUsername}}
      dockerHubContainerName: ${{secrets.dockerHubContainerName}}    
      commitSHA: ${{github.event.pull_request.head.sha}}
    steps:
    - uses: actions/checkout@v1
      
    - name: Build Container
      run: docker build -f "dotnet3.Dockerfile" -t "${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}}:ubuntu" .

    - name: Push to Docker Hub
      run: |
        echo ${{secrets.dockerHubPassword}} | docker login -u ${{secrets.dockerHubUsername}} --password-stdin
        docker push "${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}}:ubuntu"
        docker logout

    - name: Prepare For Deployment
      shell: bash
      run: |
        chmod -R a+x scripts
        echo "${{secrets.digitalOceanPrivateKey}}" >> key.txt
        chmod 600 key.txt
        echo "^[containers^]" > inventory
        echo "DigitalOceanContainer1 ansible_user=root ansible_ssh_host=${{secrets.digitalOceanIP}} domain=${{secrets.domain}} containerName=${{secrets.dockerHubContainerName}} containerImage='${{secrets.dockerHubUsername}}/${{secrets.dockerHubContainerName}}:ubuntu'  ansible_ssh_private_key_file=key.txt ansible_ssh_extra_args='-o StrictHostKeyChecking=no'" >> inventory
        ## You can dynamically add more containers here if you want to test different container environments
        
    - name: Deploy Public Facing Containers
      run: ansible-playbook -i inventory scripts/deploy.yml
          
    - name: Check Home Page of All Ubuntu Containers
      run: ansible-playbook -i inventory scripts/checkpage.yml
      
    - name: Delete Private Key Text File
      run: rm key.txt
